name: Run Postman API Tests

on:
  push:

jobs:
  postman-tests:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js (for Newman)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Newman
        run: npm install -g newman

      - name: Create folder for report
        run: mkdir newman

      - name: Run API Tests with Newman
        run: >
          newman run Shop_API_Testing.postman_collection.json 
          -e QA.postman_environment.json 
          -r cli,junit 
          --reporter-junit-export=newman/Shop_API_Testing-report.xml

      - name: Upload JUnit report artifact
        uses: actions/upload-artifact@v4
        with:
          name: postman-junit-report
          path: newman/Shop_API_Testing-report.xml

      - name: Upload Newman Report
        uses: actions/upload-artifact@v4
        with:
          name: newman-report
          path: newman/Shop_API_Testing-report.xml

