name: Run Postman API Tests

on:
  push:

jobs:
  automated-api-tests:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Newman
        run: npm install -g newman

      - name: Create report folder
        run: |
          if (-Not (Test-Path "postman-tests")) {
            New-Item -ItemType Directory -Path "postman-tests"
          }

      - name: Install newman HTML reporting
        run: npm install -g newman-reporter-html
      
      - name: Run Newman Collection
        run: |
          newman run Shop_API_Testing.postman_collection.json `
            -e QA.postman_environment.json `
            -r html `
            --reporter-html-export postman-tests/newman1/report.html
    
          # After the "Run Newman Collection" step

      - name: Verify report generation
        run: |
          Get-ChildItem -Recurse postman-tests # For Windows runner

# After the "Run Newman Collection" step

      - name: Upload Newman Report
        uses: actions/upload-artifact@v4
        with:
          name: Newman_API_Report
          path: postman-tests/newman1/report.html

        
        
