name: Run Postman Tests

on:
  push:
    branches:
      - main

jobs:
  postman-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install Newman and JUnit reporter
      run: |
        npm install -g newman newman-reporter-junitfull
    - name: Run Newman collection with JUnit report
      run: |
        newman run Shop_API_Testing.postman_collection.json \
        -e QA.postman_environment.json \
        --reporters cli,junitfull \
        --reporter-junitfull-export newman-results.xml
    - name: Upload JUnit report as artifact
      uses: actions/upload-artifact@v3
      with:
        name: junit-postman-report
        path: newman-results.xml
